services:
  - type: web
    name: localhub-backend
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn localhub_backend.localhub_backend.localhub_backend.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: localhub-db
          property: connectionString
      - key: PAYPAL_CLIENT_ID
        value: ASx0-9gXkqS-qpezITG8adHrUhnltD_grSJcb5UFT0MKa5R8Zx7hpS57qS25iqNM8kaHJ_hYfPRLOfyM
      - key: PAYPAL_SECRET
        value: EHJM7sEOchw4mKtHIMS0UXS_P8eKHdJpIXtBHNy6dlaCCOGZwVm2NxGDE6gGLvjms-i4BvH5nyoZVZFs
      - key: PAYPAL_ENV
        value: sandbox

databases:
  - name: localhub-db
    plan: free
