# Generated by Django 5.2.1 on 2025-06-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationlog',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='moderationlog',
            name='action_taken',
            field=models.CharField(choices=[('warned', 'Warned'), ('banned', 'Banned'), ('content_deleted', 'Content Deleted'), ('no_action', 'No Action Taken')], max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(choices=[('inappropriate', 'Inappropriate'), ('spam', 'Spam'), ('abuse', 'Abuse'), ('other', 'Other')], max_length=20),
        ),
    ]
