# Generated by Django 5.2.1 on 2025-06-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_assignment_assignmentsubmission_quiz_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='submission_file',
            field=models.FileField(upload_to='media/assignments/'),
        ),
    ]
