# Generated by Django 5.2.1 on 2025-06-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_location_latitude_location_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='material',
            field=models.FileField(blank=True, null=True, upload_to='media/material/'),
        ),
        migrations.AddField(
            model_name='resource',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='condition_report',
            field=models.FileField(blank=True, null=True, upload_to='media/reports/'),
        ),
    ]
