# Generated by Django 5.2.1 on 2025-06-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('business_name', models.CharField(max_length=100)),
                ('media', models.ImageField(upload_to='ads_media/')),
                ('valid_until', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='NGOPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='ngo_logos/')),
                ('link', models.URLField()),
            ],
        ),
    ]
