# Generated by Django 5.2.1 on 2025-06-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('stripe', 'Stripe'), ('cbebirr', 'CBE Birr'), ('telebirr', 'Telebirr')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
